dist: xenial
language: go
go:
- 1.14.x
git:
  depth: 1
install: false
notifications:
  email: true
before_script:
- go get golang.org/x/lint/golint
- curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
script:
- golangci-lint run --skip-files patterns.go
- go vet
- golint -set_exit_status
- go test -v -race ./...
before_deploy:
- GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -a -tags static_all -o lingualeo
deploy:
  provider: releases
  api_key:
    secure: U9VauoCFQoNAzHZZXd+5bjxKvfOBEUvsmtd9G5rL+XYOBctLgoWaWIoSw4ELQnjCLLI67AG67UVFI6WiDPYD40ZoavZ+vfhoh/XwJSoPkriAKkbZa1xNeyJTOhQxOwUoxuKqfQnn7fb+q0A5ql03BrodPPCXrNBkQ+oBhf3QPk/ZRCCL9LqXkkstWOX1xJN/ZbJoTsJnLjHHIaYk/VHqFo47JmGgDtD2C0DNc7TT8GOeEgtNACadUZK+dq8ski0SoAxv7vb1wPCetDFVVnuQL6+MvBP8Fh7znaU6X/EY6EweNpkGOAY0hAPA47Lpe05F0nJ/ahCVlAtC0RSELdxT3uRiPG5KzjOx1nin8PX02yNW8cIV0+NHCV8cHiXUZqQT7L+xmJBtnPVEs2SeP+gV8rOZsatOVlrh0r163du0182Gvp+yxjMwaeq949lZAzoEyxtDQFf6eqjR2ok7bA3qEp3g59Gu7KpHS9mIue2ZqPYGi+5jiRkdXNrRBkIPxZ2XHc06Shz8N81jXFXHvY8THG/w4uPZ3HD4BOqtOI26Bmg93Gf7xBuEbTIB7UiUebKBEOMa2mm7DLUau2hdnlmvuSNFxE3Tx8pcisQWYdUwTkr3OwiNc1FkWLyJQ/C7wS3/2JZxqiZgSp76q+bTY7sqda9dFxARyTtYGVHI7ylzXC4=
  file: lingualeo
  skip_cleanup: true
  on:
    tags: true