dist: xenial
language: go

go:
  - 1.13.x

git:
  depth: 1

install: false

notifications:
  email: true

before_script:
  - go get golang.org/x/lint/golint
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - golangci-lint run --skip-files patterns.go
  - go vet
  - golint -set_exit_status
  - go test -v -race ./...