dist: xenial
language: go

go:
  - 1.13.x

git:
  depth: 1

install: false

notifications:
  email: false

before_script:
  - go get golang.org/x/lint/golint

script:
  - go vet
  - golint -set_exit_status
  - go test -v -race ./...